### ISSUE TITLE
Crashing while killing enemies

### ISSUE THREAD

**Issue by DankestO** [MCTeamPotato/LookInMyEyes#1]
I'm not entirely sure what happened, but it seems like there are some enemies that crash when they see me, or maybe when I kill them?...

This happened to me three times in a row within minutes of starting to play on my dedicated server.
The problem wasn't fixed until I removed the mod, and then it didn't happen again.

Forge: 
- 1.20.1 - 47.4.0

Mod:
- 1.20.1-1.3.1-hotfix

[crash-2025-07-23_22.58.47-server.txt](https://github.com/user-attachments/files/21402559/crash-2025-07-23_22.58.47-server.txt)

**Comment by Kasualix** [comment]
Fixed in 1.3.2 (currently under review)
thx for your report

**Comment by DankestO** [comment]
Hi, sorry, I'm reporting it here so I don't have to open another similar report.

I tried the new version, and the same bug is still present. I think it has to do with the sound.

I disabled the option for mobs to hear me, and now it doesn't crash anymore.

**Comment by Kasualix** [comment]
may you upload your lastest.log on the crash?

**Comment by Kasualix** [comment]
Btw I just upload 1.4.0 to fix a [bug](https://github.com/MCTeamPotato/LookInMyEyes/blob/1.20.1-forge/CHANGELOG.md) one second ago

**Comment by DankestO** [comment]
Oh, damn, I thought the version from 4 hours ago was the one that fixed it (version 1.3.3)

Sorry.

**Comment by DankestO** [comment]
Hello again.
This time, with the update 1.20.1 - 1.4.0 the same problem continues to occur, but this time only kick from the server and does not stop.

Placing "Mobschecksoundsource" in "False" seems to be the only way to avoid this.

[latest.log](https://github.com/user-attachments/files/21443703/latest.log)

**Comment by Kasualix** [comment]
[Unzip me.zip](https://github.com/user-attachments/files/21444231/Unzip.me.zip)
May you try this build?

**Comment by DankestO** [comment]
I've been testing it for about half an hour now, with "Mobschecksoundsource" set to "true."

In my time playing, nothing unusual has happened again.

Thanks for the quick fixes, sir. I hope you have a great day!! :D
